// <auto-generated />
using System;
using KuechenRezepte.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuechenRezepte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307192312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KuechenRezepte.Models.Mahlzeit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("RezeptId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Datum")
                        .IsUnique();

                    b.HasIndex("RezeptId");

                    b.ToTable("Mahlzeiten");
                });

            modelBuilder.Entity("KuechenRezepte.Models.Rezept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BildPfad")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Portionen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zubereitung")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Zubereitungszeit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rezepte");
                });

            modelBuilder.Entity("KuechenRezepte.Models.RezeptZutat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Einheit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Menge")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RezeptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZutatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RezeptId");

                    b.HasIndex("ZutatId");

                    b.ToTable("RezeptZutaten");
                });

            modelBuilder.Entity("KuechenRezepte.Models.Zutat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Zutaten");
                });

            modelBuilder.Entity("KuechenRezepte.Models.Mahlzeit", b =>
                {
                    b.HasOne("KuechenRezepte.Models.Rezept", "Rezept")
                        .WithMany()
                        .HasForeignKey("RezeptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rezept");
                });

            modelBuilder.Entity("KuechenRezepte.Models.RezeptZutat", b =>
                {
                    b.HasOne("KuechenRezepte.Models.Rezept", "Rezept")
                        .WithMany("RezeptZutaten")
                        .HasForeignKey("RezeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuechenRezepte.Models.Zutat", "Zutat")
                        .WithMany("RezeptZutaten")
                        .HasForeignKey("ZutatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezept");

                    b.Navigation("Zutat");
                });

            modelBuilder.Entity("KuechenRezepte.Models.Rezept", b =>
                {
                    b.Navigation("RezeptZutaten");
                });

            modelBuilder.Entity("KuechenRezepte.Models.Zutat", b =>
                {
                    b.Navigation("RezeptZutaten");
                });
#pragma warning restore 612, 618
        }
    }
}
